### ISSUE TITLE
virt_guest seems to look for a template on the local system, not on the delegated system.

### ISSUE THREAD

**Issue by sigio** [ansible-provisioning/ansible-provisioning#5]
```
 - name: Create VM from template
    action: virt_guest guest=${inventory_hostname} src=/etc/libvirt/vm_templates/${inventory_hostname}.xml
    delegate_to: ${hypervisor}
    register: guest
```

Reports the following error: 

```
TASK: [Create VM from template] *********************************************** 
 ESTABLISH CONNECTION FOR USER: root on PORT 22 TO
 EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1371758995.94-206813481106577 && echo $HOME/.ansible/tmp/ansible-1371758995.94-206813481106577'
fatal: [vmtest2] => {'msg': u'unable to read /etc/libvirt/vm_templates/vmtest2.xml (/etc/libvirt/vm_templates/vmtest2.xml)', 'failed': True}
fatal: [vmtest2] => {'msg': u'unable to read /etc/libvirt/vm_templates/vmtest2.xml (/etc/libvirt/vm_templates/vmtest2.xml)', 'failed': True}

FATAL: all hosts have already failed -- aborting
```

If I then create the (empy) file /etc/libvirt/vm_templates/vmtest2.xml on my local machine (the one I run ansible on)... I get this error:

```
failed: [vmtest2] => {"failed": true, "parsed": false}
invalid output was: libvir: QEMU error : Domain not found: no domain with matching name 'vmtest2'
libvir: Domain Config error : (domain_definition):1: Document is empty
(null)
```

If I then put the generated template ( which is placed on ${hypervisor}) in this location, the play works just fine... but it should take the template from the place where the previous play/task put it... delegated to $hypervisor...

**Comment by dagwieers** [comment]
Can we close this issue ?

We are going to move everything (as much as possible) over to the Ansible repository. It would be nice to be able to close all open issues for the modules that will be moved. (Not sure if this one still has a reason to exist though ;-))

**Comment by sigio** [comment]
Don't know how relevant this is anymore... it being 3 years old ;)

**Comment by dagwieers** [comment]
Say no more :-)
